//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMe.Infrastructure.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserId { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public int Pin { get; set; }
        public string Mobile { get; set; }
        public int UserVerified { get; set; }
        public string EmailVerified { get; set; }
        public string IdUrl { get; set; }
    }
}
